version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.sxxpqp.top'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/c/Users/sxxpqp/Desktop/gitlab/config:/etc/gitlab'
      - '/c/Users/sxxpqp/Desktop/gitlab/logs:/var/log/gitlab'
      - '/c/Users/sxxpqp/Desktop/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'